name: NPM Bump Version and Tag
description: >-
  Macro to bump a package.json version to the next version and tag the commit.


inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  package-json:
    description: relative path to package.json
    required: false
    default: package.json

  commit-message:
    description: >
      Git commit message.
      Version will be appended as ` <version>`. (Space + Version).
      Empty string (default) will not create commit.
    required: false
    default: ''
  tag-message:
    description: >
      Git tag message.
      Empty string (default) will create lightweight tag.
    required: false
    default: ''

  bump_major:
    description: whether to bump version major (e.g '1.2.3' -> '2.0.0')
    required: false
    default: 'false'
  bump_minor:
    description: whether to bump version minor (e.g. '1.2.3' -> '1.3.0')
    required: false
    default: 'false'
  bump_patch:
    description: whether to bump version patch (e.g. '1.2.3' -> '1.2.4')
    required: false
    default: 'false'
  bump_prerelease:
    description: whether to bump version prerelease (e.g. '1.2.3-rc.0' -> '1.2.3-rc.1')
    required: false
    default: 'false'
  set_prerelease:
    description: new prerelease component to set (e.g. '1.2.3' -> '1.2.3-rc.0')
    required: false
    default: ''
  set_build:
    description: new build component to set (e.g. '1.2.3' -> '1.2.3+foobar')
    required: false
    default: ''
  finalize:
    description: any prerelease and build metadata from the version (e.g. '1.2.3-rc.0+foobar' -> '1.2.3')
    required: false
    default: 'false'
  numerical_limit:
    description: >
      Numerical limit (maximum) for a version component.
      e.g. .NET version components can only reach a maximum of signed-16-bit-word,
      i.e. 32767.
      This action will automatically bump the next upper component and reset the current
      component to 0
      if it exceeds the numerical_limit.
      Caveat: note that exceeding the numerical limit with the major component will
      fail.
    required: false
    default: '32767'

outputs:
  version:
    description: bumped version
    value: ${{steps.bump-version.outputs.version}}

runs:
  using: composite
  steps:
  - id: bump-version
    name: Bump package.json version
    uses: kagekirin/gha-py-toolbox/macros/npm/bump-version@main
    with:
      version: ${{steps.compare.outputs.greater}}
      path: ${{inputs.path}}
      package-json: ${{inputs.package-json}}
      commit-message: ${{inputs.commit-message}}
      bump_major: ${{inputs.bump_major}}
      bump_minor: ${{inputs.bump_minor}}
      bump_patch: ${{inputs.bump_patch}}
      bump_prerelease: ${{inputs.bump_prerelease}}
      set_prerelease: ${{inputs.set_prerelease}}
      set_build: ${{inputs.set_build}}
      finalize: ${{inputs.finalize}}
      numerical_limit: ${{inputs.numerical_limit}}

  - id: tag-commit
    name: Tag HEAD
    uses: kagekirin/gha-py-toolbox/actions/git/tag@main
    with:
      path: ${{inputs.path}}
      commitish: HEAD
      message: ${{inputs.tag-message}} v${{steps.bump-version.outputs.version}}
      tag: v${{steps.bump-version.outputs.version}}
