name: NPM Bump Version Tag
description: >-
  Macro to bump a package.json version to the next version.



inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  package-json:
    description: relative path to package.json
    required: false
    default: package.json

  commit-message:
    description: >
      Git commit message.
      Version will be appended as ` <version>`. (Space + Version).
      Empty string (default) will not create commit.
    required: false
    default: ''
  tag-message:
    description: >
      Git tag message.
      Empty string (default) will create lightweight tag.
    required: false
    default: ''

  bump_major:
    description: whether to bump version major (e.g '1.2.3' -> '2.0.0')
    required: false
    default: 'false'
  bump_minor:
    description: whether to bump version minor (e.g. '1.2.3' -> '1.3.0')
    required: false
    default: 'false'
  bump_patch:
    description: whether to bump version patch (e.g. '1.2.3' -> '1.2.4')
    required: false
    default: 'false'
  bump_prerelease:
    description: whether to bump version prerelease (e.g. '1.2.3-rc.0' -> '1.2.3-rc.1')
    required: false
    default: 'false'
  set_prerelease:
    description: new prerelease component to set (e.g. '1.2.3' -> '1.2.3-rc.0')
    required: false
    default: ''
  set_build:
    description: new build component to set (e.g. '1.2.3' -> '1.2.3+foobar')
    required: false
    default: ''
  finalize:
    description: any prerelease and build metadata from the version (e.g. '1.2.3-rc.0+foobar' -> '1.2.3')
    required: false
    default: 'false'
  numerical_limit:
    description: >
      Numerical limit (maximum) for a version component.
      e.g. .NET version components can only reach a maximum of signed-16-bit-word,
      i.e. 32767.
      This action will automatically bump the next upper component and reset the current
      component to 0
      if it exceeds the numerical_limit.
      Caveat: note that exceeding the numerical limit with the major component will
      fail.
    required: false
    default: '32767'

outputs:
  version:
    description: bumped version
    value: ${{steps.bump-version.outputs.version}}

runs:
  using: composite
  steps:
  - id: git-version
    name: Get latest version tag from git
    uses: kagekirin/gha-py-toolbox/actions/git/get-latest-version-tag@main
    with:
      path: ${{inputs.path}}

  - id: npm-version
    name: Get version from ${{inputs.package-json}}
    uses: kagekirin/gha-py-toolbox/actions/npm/get-version@main
    with:
      path: ${{inputs.path}}
      package-json: ${{inputs.package-json}}

  - id: compare
    name: Compare ${{steps.git-version.outputs.version}} against ${{steps.npm-version.outputs.version}}
    uses: kagekirin/gha-py-toolbox/actions/semver/compare@main
    with:
      version_A: ${{steps.git-version.outputs.version}}
      version_B: ${{steps.npm-version.outputs.version}}

  - id: bump-version
    name: Compute next version from ${{steps.compare.outputs.greater}}
    uses: kagekirin/gha-py-toolbox/actions/semver/bump-version@main
    with:
      version: ${{steps.compare.outputs.greater}}
      bump_patch: true
      finalize: true

  - id: update-package-json
    name: Update ${{inputs.package-json}}
    uses: kagekirin/gha-py-toolbox/actions/npm/set-version@main
    with:
      path: ${{inputs.path}}
      package-json: ${{inputs.package-json}}
      version: ${{steps.bump-version.outputs.version}}

  - id: commit-am
    name: Commit changes
    uses: kagekirin/gha-py-toolbox/actions/git/commit-all-modified@main
    with:
      path: ${{inputs.path}}
      message: ${{inputs.commit-message}} v${{steps.bump-version.outputs.version}}

  - id: tag-commit
    name: Tag HEAD
    uses: kagekirin/gha-py-toolbox/actions/git/tag@main
    with:
      path: ${{inputs.path}}
      commitish: HEAD
      message: ${{inputs.tag-message}} v${{steps.bump-version.outputs.version}}
      tag: v${{steps.bump-version.outputs.version}}
