name: GIT rebase branch Xtheirs
description: >
  Rebase branch from given base branch
  Runs `git rebase [branch] -Xtheirs`.

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  branch:
    description: >
      (Head) Branch to rebase.
      If empty (default), do not switch branches before running command.
    required: false
    default: ''
  base:
    description: >
      Base branch (or commit-ish) to rebase from.
      If empty (default), uses default branch (usually main or master).
    required: false
    default: ''

runs:
  using: composite
  steps:
  - id: rebase-xtheirs
    uses: kagekirin/gha-py-toolbox/actions/git/rebase@main
    with:
      options: -Xtheirs
      path: ${{inputs.path}}
      branch: ${{inputs.branch}}
      base: ${{inputs.base}}
