name: INSTALL via apt-get
description: >-
  Installs apt packages via apt-get (for Ubuntu/Debian and compatible or derivatives).

inputs:
  packages:
    description: >
      Packages to install.
      Expects a whitespace-separated list, so use YAML `>`, `>-`, `|` or `|-`.
    required: true
  sudo:
    description: >
      'sudo' or 'su -u user' when required.
      Default is empty.
    required: false
    default: ''

runs:
  using: composite
  steps:
  - id: apt-get-install
    name: Install via APT-GET
    shell: python
    env:
      packages: ${{inputs.packages}}
      sudo: ${{inputs.sudo}}
    run: |
      ## actions/install/apt-get/action.yml#apt-get-install
      import os, sys

      packages = str(os.getenv("packages")).split()
      sudo = str(os.getenv("sudo"))

      update_cmd = ["apt-get", "update", "-y", "-qq"]
      install_cmd = ["apt-get", "install", "-y"]

      if sudo and len(sudo):
          update_cmd = sudo.split() + update_cmd
          install_cmd = sudo.split() + install_cmd

      command = " ".join(update_cmd)
      print(command, flush=True)
      err = os.waitstatus_to_exitcode(os.system(command))
      assert err == 0

      command = " ".join(install_cmd + packages)
      print(command, flush=True)
      err = os.waitstatus_to_exitcode(os.system(command))
      assert err == 0
      exit(err)
