name: NUGET get packages versions
description: >
  Retrieves a list of available versions for several NUGET packages.

  The returned structure maps the package name to its versions.

  NOTE: All packages must be available on the same registry.

inputs:
  token:
    description: >
      GitHub (Enterprise): token with "packages:read" permissions for the given repository.
      Defaults to empty string for nuget.org.
    required: false
    default: ''
  registry:
    description: >
      Registry URL from where to fetch the package, without the terminal path `index.json`.
      Defaults to official NuGet registry.
    required: false
    default: https://api.nuget.org/v3/index.json
  packages:
    description: >
      Package names.
      Space-separated list.
    required: true

outputs:
  packages:
    description: >-
      JSON string of the packages along with their versions (dict).

      GitHub Actions cannot return objects, hence only the JSON string is possible.
      To retrieve the object, use $ {{ fromJSON(steps.this-step.outputs.index) }}.
      fromJSON(fromJSON()) is the correct way to retrieve the object

      The `fromJSON` below transforms the escaped string into an unescaped one.
    value: ${{fromJSON(steps.get-packages-versions.outputs.indices)}}
  base-url:
    description: first encountered value for "PackageBaseAddress"
    value: ${{steps.get-packages-versions.outputs.base_url}}

runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: kagekirin/gha-py-toolbox/actions/pip/install@main
    with:
      packages: >-
        requests

  - id: get-packages-versions
    name: Get packages versions
    shell: python
    env:
      inputs_registry: ${{inputs.registry}}
      inputs_token: ${{inputs.token}}
      inputs_packages: ${{inputs.packages}}
    run: |
      import os, sys, json, pprint, requests
      from urllib.parse import urlparse, urljoin

      session = requests.Session()

      registry_url = str(os.getenv("inputs_registry"))
      assert urlparse(registry_url)
      if not registry_url.endswith("/"):
          registry_url = registry_url + "/"
      print(f"registry_url: {registry_url}")
      assert urlparse(registry_url)

      token = str(os.getenv("inputs_token", os.getenv("GITHUB_TOKEN", "")))
      print(f"token: {token}")
      if token and len(token) > 0:
          session.headers["Authorization"] = f"Bearer {token}"
          session.headers["X-NuGet-ApiKey"] = token
      session.headers["X-NuGet-Protocol-Version"] = "4.1.0"
      pprint.pp(session.headers)

      index_url = urljoin(registry_url, "index.json")
      assert urlparse(index_url)
      print(f"fetching {index_url}")

      index_response = session.get(index_url)
      assert index_response is not None
      print(index_response.status_code, index_response.reason)
      assert index_response.ok

      index_data = index_response.json()
      assert index_data
      pprint.pp(index_data)
      print(json.dumps(index_data, indent=2))

      ## retrieve 'PackageBaseAddress' from resources
      resources = index_data["resources"]
      assert resources
      pprint.pp(resources)

      base_url = list(
          filter(
              lambda item: item["@type"].startswith("PackageBaseAddress"),
              resources,
          )
      )[0]["@id"]
      assert urlparse(base_url)
      print(f"base_url: {base_url}")
      if not base_url.endswith("/"):
          base_url = f"{base_url}/"
      assert urlparse(base_url)

      packages = str(os.getenv("inputs_packages")).split()
      packages_data = dict()
      for package_name in packages:
          print(f"package_name: {package_name}")
          assert package_name
          assert len(package_name)

          package_url = urljoin(base_url, f"{package_name.lower()}/index.json")
          assert urlparse(package_url)
          print(f"fetching {package_url}")

          package_response = session.get(package_url)
          assert package_response is not None
          print(package_response.status_code, package_response.reason)
          assert package_response.ok

          package_data = package_response.json()
          assert package_data
          pprint.pp(package_data)
          packages_data[package_name] = package_data["versions"]

      packages_json_escaped = json.dumps(json.dumps(packages_data, sort_keys=True))
      print(packages_json_escaped)

      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"packages={packages_json_escaped}")
          print(f"packages={packages_json_escaped}", file=fh)
          print(f"base_url={base_url}")
          print(f"base_url={base_url}", file=fh)

  - id: verify-outputs
    name: Verify
    shell: cat {0}
    run: |
      steps.get-packages-versions.outputs.packages
      ${{steps.get-packages-versions.outputs.packages}}
      fromJSON ${{fromJSON(steps.get-packages-versions.outputs.packages)}}
      fromJSON(fromJSON) ${{fromJSON(fromJSON(steps.get-packages-versions.outputs.packages))}}

      ===========================================

      steps.get-packages-versions.outputs.base_url
      ${{steps.get-packages-versions.outputs.base_url}}
