name: NUGET increment packages versions
description: >
  Retrieves and filters the packages referenced by a given project or props file.

  Returns a JSON string of a dictionary mapping package name to its version.

inputs:
  token:
    description: >
      GitHub (Enterprise): token with "packages:read" permissions for the given repository.
      Defaults to empty string for nuget.org.
    required: false
    default: ''
  registry:
    description: >
      Registry URL from where to fetch the package, without the terminal path `index.json`.
      Defaults to official NuGet registry.
    required: false
    default: https://api.nuget.org/v3/
  packages:
    description: >
      JSON dictionary mapping packages to their current version.
    required: true
  method:
    description: >
      Increment method: `increment` to go to the next higher version or `latest`.
    type: choice
    options:
    - increment
    - latest
    required: true

outputs:
  packages:
    description: dictionary mapping the retrieved packages to their respective incremented
      versions
    value: ${{ steps.increment-package-versions.outputs.packages }}

runs:
  using: composite
  steps:
  - id: get-package-names
    name: Get package names
    shell: python
    env:
      inputs_packages: ${{ inputs.packages }}
    # split keys (package names) from the input dict
    run: |
      import os, json

      packages_json_escaped = str(os.getenv("inputs_packages"))
      assert packages_json_escaped
      packages = json.loads(json.loads(packages_json_escaped))
      assert packages

      package_names = packages.keys()
      packages_json_escaped = json.dumps(json.dumps(packages, sort_keys=True))
      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"packages={packages_json_escaped}")
          print(f"packages={packages_json_escaped}", file=fh)

  - id: get-packages-versions
    name: Get package index for each package
    uses: kagekirin/gha-py-toolbox/actions/nuget/get-packages-versions@main
    with:
      token: ${{ inputs.token }}
      registry: ${{ inputs.registry }}
      packages: ${{ steps.get-package-names.outputs.packages }}

  - id: increment-package-versions
    name: Increment package versions
    uses: kagekirin/gha-py-toolbox/actions/semver/increment-packages-versions@main
    with:
      packages: ${{ inputs.packages }}
      versions: ${{ steps.get-packages-versions.outputs.packages }}
      method: ${{ inputs.method }}
