name: GH MACRO download published registry_package
description: >
  Downloads published registry package files using the following actions:
  - gh/download-published-nuget-package
  - gh/download-published-npm-package
  - gh/download-published-package

  Returns a whitespace-separated list of the downloaded packages, i.e.
  the result of joining the outputs from the aforementioned actions.

  This can only be called from a `on-registry_package[published]` job as below,
  as it requires the data structure specific to `github.event.registry_package`.
  Further, permissions must be set as below:

  ```
  on:
    registry_package:
      types: [published]

  jobs:
    upload:
      permissions:
        packages: read  #<-- access packages
    runs-on: xxx-latest
    steps:
    - id: download-package
      name: Download published package
      uses: kagekirin/gha-py-toolbox/actions/gh/download-published-npm-package@main
      with:
        registry_package_json: $ {{ toJSON(github.event.registry_package) }}
        token: $ {{ github.token }}
  ```

inputs:
  token:
    description: >
      GitHub (Enterprise): token with "packages:read" permissions for the given repository.
    required: false
    default: ${{github.token}}
  registry_package_json:
    description: >
      The github.event.registry_package structure as JSON string:

      ```
      registry_package_json: $ {{ toJSON(github.event.registry_package) }}
      ```
    required: true

outputs:
  packages:
    description: >
      Whitespace-separated list of the downloaded package files.
    value: ${{join([steps.download-nuget-package.outputs.packages,steps.download-npm-package.outputs.packages,steps.download-package.outputs.packages],' ')}}

runs:
  using: composite
  steps:
  - id: download-nuget-package
    if: ${{fromJSON(registry_package_json).ecosystem == 'nuget'}}
    name: Download published NuGet package
    uses: kagekirin/gha-py-toolbox/macros/gh/download-published-nuget-package@main
    with:
      registry_package_json: ${{inputs.registry_package_json}}
      token: ${{inputs.token}}

  - id: download-npm-package
    if: ${{fromJSON(registry_package_json).ecosystem == 'npm'}}
    name: Download published NPM package
    uses: kagekirin/gha-py-toolbox/actions/gh/download-published-npm-package@main
    with:
      registry_package_json: ${{inputs.registry_package_json}}
      token: ${{inputs.token}}

  - id: download-package
    if: ${{format('{0}{1}', steps.download-nuget-package.outputs.packages, steps.download-npm-package.outputs.packages) == ''}}
    name: Download published generic package files
    uses: kagekirin/gha-py-toolbox/actions/gh/download-published-package@main
    with:
      registry_package_json: ${{inputs.registry_package_json}}
      token: ${{inputs.token}}
