name: .NET MACRO Restore, Build & Pack
description: >
  Macro action performing the following:
  * dotnet-restore
  * dotnet-build
  * dotnet-pack

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  configurations:
    description: >
      configuration(s) to build for (Debug, Release, ...).
      empty string (default) defers to project/solution defaults.
      whitespace separated list.
    required: false
    default: ''
  frameworks:
    description: >
      framework(s) to build for (net8.0, netstandard2.1, ...).
      empty string (default) defers to project/solution defaults.
      whitespace separated list.
    required: false
    default: ''
  projects:
    description: >
      project(s) to build
      empty string (default) defers to project defaults
      whitespace separated list. can use glob pattern.
      empty string (default) defers to solution.
    required: false
    default: ''

  restore-options:
    description: >
      supplementary command line options forwarded to `dotnet restore`
      whitespace separated list.
    required: false
    default: ''
  build-options:
    description: >
      supplementary command line options forwarded to `dotnet build`
      whitespace separated list.
    required: false
    default: ''
  pack-options:
    description: >
      supplementary command line options forwarded to `dotnet pack`
      whitespace separated list.
    required: false
    default: ''
  filter-packages:
    description: >
      optional set of regular expressions to filter out packages to not publish.
      whitelist, i.e. only matching packages will be published.
      empty string (default) is equivalent to /.*/ (match all)
    required: false
    default: ''

  nuget-cache:
    description: >
      path(s) to cache for nuget packages.
      empty (default): no cache
    required: false
    default: ''
  build-cache:
    description: >
      path(s) to cache for build artifacts.
      empty (default): no cache
    required: false
    default: ''

outputs:
  packages:
    description: >
      whitespace-separated list of created .nupkg files
    value: ${{steps.pack.outputs.packages}}

runs:
  using: composite
  steps:
  - uses: kagekirin/gha-py-toolbox/macros/dotnet/build@main
    with:
      path: ${{inputs.path}}
      projects: ${{inputs.projects}}
      configurations: ${{inputs.configurations}}
      frameworks: ${{inputs.frameworks}}

      restore-options: ${{inputs.restore-options}}
      build-options: ${{inputs.build-options}}

      nuget-cache: ${{inputs.nuget-cache}}
      build-cache: ${{inputs.build-cache}}

  - id: pack
    uses: kagekirin/gha-py-toolbox/actions/dotnet/pack@main
    with:
      path: ${{inputs.path}}
      projects: ${{inputs.projects}}
      configurations: ${{inputs.configurations}}
      frameworks: ${{inputs.frameworks}}
      options: ${{inputs.pack-options}}
      filter-packages: ${{inputs.filter-packages}}
