name: INSTALL via NPM
description: >-
  Installs node tool packages via npm.
  Requires NodeJS and npm command to be installed.

inputs:
  packages:
    description: >
      Packages to install.
      Expects a whitespace-separated list, so use YAML `>`, `>-`, `|` or `|-`.
    required: true
  sudo:
    description: >
      'sudo' or 'su -u user' when required.
      Default is empty.
    required: false
    default: ''

runs:
  using: composite
  steps:
  - id: brew-install
    name: Install via BREW
    shell: python
    env:
      packages: ${{inputs.packages}}
      sudo: ${{inputs.sudo}}
    run: |
      ## actions/install/npm-tool/action.yml#brew-install
      import os, sys

      packages = str(os.getenv("packages")).split()
      sudo = str(os.getenv("sudo"))

      install_cmd = ["npm", "install", "-g"]

      if sudo and len(sudo):
          install_cmd = sudo.split() + install_cmd

      err = 0
      for package in packages:
          command = " ".join(install_cmd + [package])
          print(command, flush=True)
          err = os.waitstatus_to_exitcode(os.system(command))
          assert err == 0

      exit(err)
