name: YAML get value
description: >-
  Retrieves the value for a given YAMLpath.

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  yaml-file:
    description: relative path to YAML file to parse
    required: false
  yaml-text:
    description: alternative YAML text to parse
    required: false
  yaml-path:
    description: YAML path expression to get value for.
    required: true

outputs:
  value:
    description: the retrieved value
    value: ${{steps.get-value.outputs.value}}

runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: kagekirin/gha-py-toolbox/actions/pip/install@main
    with:
      packages: >-
        pyyaml
        jsonpath-ng
        detect-indent

  - id: get-value
    name: Get ${{inputs.path}} .${{inputs.yaml-path}}
    shell: python
    env:
      inputs_path: ${{inputs.path}}
      inputs_yaml_file: ${{inputs.yaml-file}}
      inputs_yaml_text: ${{inputs.yaml-text}}
      inputs_yaml_path: ${{inputs.yaml-path}}
    run: |
      ## actions/yaml/get-value/action.yml#get-value
      import os, sys, json, yaml, pprint
      import jsonpath_ng.ext as jsonpath
      from pathlib import Path

      os.chdir(os.getenv("GITHUB_WOKRDIR", "."))

      inputs_path = os.getenv("inputs_path", ".")
      inputs_yaml_file = os.getenv("inputs_yaml_file")
      inputs_yaml_text = os.getenv("inputs_yaml_text")
      inputs_yaml_path = os.getenv("inputs_yaml_path")

      yaml_path = jsonpath.parse(str(inputs_yaml_path))
      print(yaml_path)

      yaml_text = None
      if inputs_yaml_file is not None:
          yaml_file = Path(inputs_path).joinpath(inputs_yaml_file)
          assert yaml_file.exists()
          if not yaml_file.exists():
              print(f"{yaml_file} does not exist")
              exit(1)

          yaml_text = yaml_file.read_text()

      if inputs_yaml_text is not None:
          yaml_text = str(inputs_yaml_text)

      yaml_data = yaml.safe_load(yaml_text)
      assert yaml_data is not None
      if yaml_data is None:
          print(f"{yaml_text} could not be parsed")
          exit(2)

      print("retrieving data:")
      output = [m.value for m in yaml_path.find(yaml_data)]
      pprint.pp(output)

      value = None
      if len(output) > 1 or type(output) is dict:
          value = json.dumps(json.dumps(output, sort_keys=True))
      elif type(output[0]) is dict:
          value = json.dumps(json.dumps(output[0], sort_keys=True))
      else:
          value = json.dumps(output[0])

      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"value={value}")
          print(f"value={value}", file=fh)
