name: UNITY cached installer-based setup
description: >-
  Downloads and installs Unity at the given version/changeset and for the given platform
  using the official installer.
  Results are cached for faster workflows.

  **WARNING: only Linux supported for now**

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}

  version:
    description: >-
      Unity version to install.
      Refer to https://unity.com/releases/editor/archive for the correct version.
    required: true
    default: 2021.3.21f1
  changeset:
    description: >-
      Unity changeset to install.
      Refer to https://unity.com/releases/editor/archive for the correct changeset.

      NOTE: The changeset is part of the actual download URL, i.e. https://download.unity3d.com/download_unity/{changeset}
      e.g.: https://download.unity3d.com/download_unity/1b156197d683/LinuxEditorInstaller/Unity-2021.3.21f1.tar.xz
    required: true
    default: 1b156197d683
  components:
    description: >-
      List of Unity components to install.

      Multiline, use whitespace/newline to separate items.
    required: true
    default: |
      Linux-IL2CPP
      Linux-Server
      WebGL
  accept-license:
    description: >-
      Whether you accept the Unity license.

      Must be explicitly set by the caller.
    required: true
  unity-path:
    description: path where to install Unity to
    required: true
    default: .unity
  unity-temp:
    description: temp path where to download Unity installers to
    required: true
    default: .unitysetup
  cache-prefix:
    description: Prefix for cache to make it unique
    required: true
    default: UCIS

outputs:
  unity-exe:
    description: full path to Unity executable
    value: ${{steps.get-unity-exe.outputs.unity-exe}}
  editor-path:
    description: full path to Unity installation folder
    value: ${{steps.get-unity-exe.outputs.editor-path}}


runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: kagekirin/gha-py-toolbox/actions/pip/install@main
    with:
      packages: >-
        requests

  - id: installer-url
    name: Generate installer URL for Unity ${{inputs.version}} and ${{inputs.changeset}}
    shell: python
    env:
      inputs_path: ${{inputs.path}}
      unity_version: ${{inputs.version}}
      unity_changeset: ${{inputs.changeset}}
      unity_baseurl: https://download.unity3d.com/download_unity/
    run: |
      ## actions/unity/cached-installer-setup/action.yml#installer-url
      import os, sys
      from urllib.parse import urlparse
      from posixpath import join
      from contextlib import chdir

      os.chdir(os.getenv("GITHUB_WOKRDIR", "."))

      unity_version = str(os.getenv("unity_version"))
      unity_changeset = str(os.getenv("unity_changeset"))

      unity_baseurl = str(os.getenv("unity_baseurl"))
      assert unity_baseurl is not None
      assert urlparse(unity_baseurl) is not None

      installer_url = join(
          unity_baseurl, unity_changeset, f"UnitySetup-{unity_version}"
      )

      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"url={installer_url}")
          print(f"url={installer_url}", file=fh)

  - id: restore-download-cache
    name: Restore download cache
    uses: actions/cache/restore@v4
    with:
      path: ${{inputs.unity-temp}}
      key: ${{inputs.cache-prefix }}-${{runner.os}}-${{inputs.unity-temp}}-${{inputs.version}}-${{inputs.changeset}}

  - id: download-installer
    if: ${{ !fromJSON(steps.restore-download-cache.outputs.cache-hit) }}
    name: Download installer from ${{steps.installer-url.outputs.url}}
    shell: python
    env:
      inputs_path: ${{inputs.path}}
      installer_url: ${{steps.installer-url.outputs.url}}
      unity_temp: ${{inputs.unity-temp}}
    run: |
      ## actions/unity/cached-installer-setup/action.yml#download-installer
      import os, sys, requests, shutil
      from pathlib import Path
      from urllib.parse import urlparse

      os.chdir(os.getenv("GITHUB_WOKRDIR", "."))

      unity_temp = Path(os.getenv("unity_temp"))
      unity_temp.mkdir(parents=True, exist_ok=True)

      installer_url = str(os.getenv("installer_url"))
      assert installer_url is not None
      assert urlparse(installer_url) is not None

      installer_path = Path.joinpath(unity_temp, Path(installer_url).name)

      with requests.get(installer_url, stream=True) as r:
          if not r.ok:
              print(
                  f"failed to access {installer_url} with status {r.status_code} {r.reason}"
              )
          assert r.ok
          if r.ok:
              with installer_path.open("wb") as fh:
                  shutil.copyfileobj(r.raw, fh)
              installer_path.chmod(0o777)

      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"path={installer_path}")
          print(f"path={installer_path}", file=fh)

  - id: save-download-cache
    name: Save download cache
    uses: actions/cache/save@v4
    with:
      path: ${{inputs.unity-temp}}
      key: ${{steps.restore-download-cache.outputs.cache-primary-key}}


  - id: restore-installation-cache
    name: Restore installation cache
    uses: actions/cache/restore@v4
    with:
      path: ${{inputs.unity-path}}
      key: ${{inputs.cache-prefix }}-${{runner.os}}-${{inputs.unity-path}}-${{inputs.version}}-${{inputs.changeset}}-${{ join(inputs.components, '-') }}

  - id: run-installer
    if: ${{ !fromJSON(steps.restore-installation-cache.outputs.cache-hit) }}
    name: Download installer from ${{steps.installer-url.outputs.url}}
    shell: python
    env:
      inputs_path: ${{inputs.path}}
      installer_path: ${{steps.download-installer.outputs.path}}
      unity_path: ${{inputs.unity-path}}
      unity_components: |
        Unity
        ${{inputs.components}}
      accept_license: ${{inputs.accept-license}}
    run: |
      ## actions/unity/cached-installer-setup/action.yml#run-installer
      import os, sys, requests, subprocess
      from pathlib import Path

      os.chdir(os.getenv("GITHUB_WOKRDIR", "."))

      installer_path = Path(os.getenv("installer_path"))
      unity_path = Path(os.getenv("unity_path"))
      unity_components = set(str(os.getenv("unity_components")).split())
      accept_license = os.getenv("accept_license") == "true"

      assert installer_path.exists()
      subprocess.run([installer_path, "--help"], check=True)
      subprocess.run(
          [installer_path, "--unattended", "--list-components"], check=True
      )
      subprocess.run(
          [
              installer_path,
              "--unattended",
              f"--install-location={unity_path.absolute()}",
              f'--components={",".join(unity_components)}',
          ],
          input="y" if accept_license else "n",
          check=True,
          text=True,
      )

  - id: save-installation-cache
    name: Save installation cache
    uses: actions/cache/save@v4
    with:
      path: ${{inputs.unity-path}}
      key: ${{steps.restore-installation-cache.outputs.cache-primary-key}}

  - id: get-unity-exe
    name: Get Unity executable
    uses: kagekirin/gha-py-toolbox/actions/unity/get-unity-exe@main
    with:
      unity-path: ${{inputs.unity-path}}
