name: INSTALL via Homebrew
description: >-
  Installs packages via Homebrew (for macOS and Linux).
  Requires Homebrew and brew command to be installed.

inputs:
  packages:
    description: >
      Packages to install.
      Expects a whitespace-separated list, so use YAML `>`, `>-`, `|` or `|-`.
    required: true
  sudo:
    description: >
      'sudo' or 'su -u user' when required.
      Default is empty.
    required: false
    default: ''

runs:
  using: composite
  steps:
  - id: brew-install
    name: Install via BREW
    shell: python
    env:
      packages: ${{ inputs.packages }}
      sudo: ${{ inputs.sudo }}
    run: |
      import os, sys

      packages = str(os.getenv("packages")).split()
      sudo = str(os.getenv("sudo"))

      install_cmd = ["brew", "install"]

      if sudo and len(sudo):
          install_cmd = sudo.split() + install_cmd

      command = " ".join(install_cmd + packages)
      print(command)
      err = os.system(command)
      assert err == 0
      exit(err)
