name: UNITY increment packages versions
description: >
  Performs the following steps:

  1. Retrieves packages from configuration file (manifest.json and/or package.json)
     that match a given filter expression.
  2. For each filter package, retrieves the next-incremental/latest version
     from a given UPM (Unity NPM) registry.
  3. Updates the configuration file (see above) with the update versions.
  4. Split changes into line-by-line patches and commit them
  5. PR creation NOT IMPLEMENTED HERE: create PR in calling action/workflow

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  upm-token:
    description: >
      GitHub (Enterprise): token with "packages:read" permissions for the given repository.
      Defaults to empty string for https://packages.unity.com.
    required: false
    default: ''
  upm-registry:
    description: >
      Registry URL to filter by scopedRegistries **if** manifest.json exists.
      Ignored if it doesn't and everything is handled using the provided registry as sole registry.

      Defaults to official Unity NPM registry: https://packages.unity.com
    required: false
    default: https://packages.unity.com
  package-regex:
    description: >
      Whitespace-separated list.
    required: true
  configuration-files:
    description: >
      Configuration file (manifest.json or package.json) to check for packages.
      Defaults to package.json.
    required: false
    default: package.json
  upm-configuration-file:
    description: >
      UPM Configuration file (manifest.json) to check for registry mapping.
      Defaults to Packages/manifest.json.

      Can be set to empty string (''), in which case only the provided registry will be considered.
    required: false
    default: Packages/manifest.json

  method:
    description: >
      Increment method: `increment` to go to the next higher version or `latest`.
    type: choice
    options:
    - increment
    - latest
    required: true

  ## Committer
  commit-username:
    description: >
      Author user.name to use.
      Defaults to triggering_actor
    required: false
    default: ${{ github.workflow }} on behalf of ${{ github.triggering_actor }}
  commit-useremail:
    description: >
      Author user.email to use.
      Defaults actor anonymous email address, `ID+USERNAME@users.noreply.github.com`
    required: false
    default: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com

  ## Commit message
  commit-message:
    description: >
      Subject to write into patch header
      Pystache template, getting fed {'package': 'foobar', 'value': '1.2.3'} from created from inputs.packages
    required: false
    default: ''

  dry-run:
    description: >
      Whether to actually push the changes and create a pullrequest.
    required: true
    default: 'true'


runs:
  using: composite
  steps:
  - id: get-package-versions
    name: Get package versions for input package names
    uses: kagekirin/gha-py-toolbox/actions/unity/get-packages-versions@main
    with:
      path: ${{ inputs.path }}
      registry: ${{ inputs.upm-registry }}
      package-regex: ${{ inputs.package-regex }}
      configuration-files: ${{ inputs.configuration-files }}
      upm-configuration-file: ${{ inputs.upm-configuration-file }}

  - id: increment-package-versions
    name: Increment versions for filtered packages
    uses: kagekirin/gha-py-toolbox/macros/npm/increment-packages-versions@main
    with:
      token: ${{ inputs.upm-token }}
      registry: ${{ inputs.upm-registry }}
      method: ${{ inputs.method }}
      packages: ${{ steps.get-package-versions.outputs.packages }}

  - id: set-packages-versions
    name: Set updated package version for each package
    uses: kagekirin/gha-py-toolbox/actions/npm/set-packages-versions@main
    with:
      path: ${{ inputs.path }}
      configuration-files: ${{ inputs.configuration-files }}
      packages: ${{ steps.increment-package-versions.outputs.packages }}

  - id: commit-packages-versions
    name: Set updated package version for each package
    uses: kagekirin/gha-py-toolbox/macros/npm/commit-packages-versions@main
    with:
      path: ${{ inputs.path }}
      configuration-files: ${{ inputs.configuration-files }}
      packages: ${{ steps.increment-package-versions.outputs.packages }}
      commit-username: ${{ inputs.commit-username }}
      commit-useremail: ${{ inputs.commit-useremail }}
      commit-message: ${{ inputs.commit-message }}
