name: UNITY cached setup
description: >-
  Downloads and installs Unity at the given version/changeset and for the given platform
  using the release tarballs.
  Results are cached for faster workflows.

  **WARNING: only Linux supported for now**

inputs:
  version:
    description: >-
      Unity version to install.
      Refer to https://unity.com/releases/editor/archive for the correct version.
    required: true
    default: 2021.3.21f1
  changeset:
    description: >-
      Unity changeset to install.
      Refer to https://unity.com/releases/editor/archive for the correct changeset.

      NOTE: The changeset is part of the actual download URL, i.e. https://download.unity3d.com/download_unity/{changeset}
      e.g.: https://download.unity3d.com/download_unity/1b156197d683/LinuxEditorInstaller/Unity-2021.3.21f1.tar.xz
    required: true
    default: 1b156197d683
  components:
    description: >-
      List of Unity components to install.

      Multiline, use whitespace/newline to separate items.
    required: true
    default: |
      Unity
      Linux-IL2CPP
      Linux-Server
      WebGL
  unity-path:
    description: path where to install Unity to
    required: true
    default: .unity
  unity-temp:
    description: temp path where to download Unity installers to
    required: true
    default: .unitysetup

outputs:
  unity-path:
    description: full path to where Unity has been installed.
    value: ${{ steps.bump-version.outputs.unity-path }}

runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: kagekirin/gha-py-toolbox/actions/pip/install@main
    with:
      packages: >-
        requests

  - id: download-url
    name: Generate download URL for Unity ${{ inputs.version }} and ${{ inputs.changeset }}
    shell: python
    env:
      unity_changeset: ${{ inputs.changeset }}
      unity_baseurl: https://download.unity3d.com/download_unity/
    run: |
      import os, sys
      from urllib.parse import urlparse, urljoin

      unity_version = str(os.getenv("unity_version"))
      unity_changeset = str(os.getenv("unity_changeset"))
      unity_baseurl = urlparse(os.getenv("unity_baseurl"))

      installer_url = urljoin(unity_baseurl.geturl(), unity_changeset)

      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"url={installer_url}/")
          print(f"url={installer_url}/", file=fh)

  - id: download-editor
    name: Download Unity Editor from ${{ steps.download-url.outputs.url }}
    shell: python
    env:
      download_url: ${{ steps.download-url.outputs.url }}
      unity_version: ${{ inputs.version }}
      unity_temp: ${{ inputs.unity-temp }}
    run: |
      import os, sys, requests, shutil
      from pathlib import Path
      from urllib.parse import urlparse, urljoin

      unity_temp = Path(os.getenv("unity_temp"))
      unity_temp.mkdir(parents=True, exist_ok=True)
      unity_version = str(os.getenv("unity_version"))

      download_url = urlparse(os.getenv("download_url"))
      editor_url = urlparse(
          urljoin(
              download_url.geturl(),
              f"LinuxEditorInstaller/Unity-{unity_version}.tar.xz",
          )
      )
      editor_path = Path.joinpath(unity_temp, Path(editor_url.geturl()).name)

      with requests.get(editor_url.geturl(), stream=True) as r:
          with editor_path.open("wb") as fh:
              shutil.copyfileobj(r.raw, fh)

      unity_temp_contents = list(unity_temp.rglob("*.*"))
      print(f"contents of {unity_temp}: {unity_temp_contents}")

  # TODO: cache editor

  - id: download-components
    name: Download Unity Components from ${{ steps.download-url.outputs.url }}
    shell: python
    env:
      download_url: ${{ steps.download-url.outputs.url }}
      unity_version: ${{ inputs.version }}
      unity_components: ${{ inputs.components }}
      unity_temp: ${{ inputs.unity-temp }}
    run: |
      import os, sys, requests, shutil
      from pathlib import Path
      from urllib.parse import urlparse, urljoin

      unity_temp = Path(os.getenv("unity_temp"))
      unity_temp.mkdir(parents=True, exist_ok=True)

      unity_version = str(os.getenv("unity_version"))
      unity_components = list(str(os.getenv("unity_components")).split())
      download_url = urlparse(os.getenv("download_url"))

      for component in unity_components:
          try:
              component_url = urlparse(
                  urljoin(
                      download_url.geturl(),
                      f"LinuxEditorTargetInstaller/UnitySetup-{component}-{unity_version}.tar.xz",
                  )
              )
              component_path = Path.joinpath(
                  unity_temp, Path(component_url.geturl()).name
              )

              with requests.get(component_url.geturl(), stream=True) as r:
                  with component_path.open("wb") as fh:
                      shutil.copyfileobj(r.raw, fh)

          except equests.exceptions.RequestException as e:
              print(f"Exception happened {e}")

      unity_temp_contents = list(unity_temp.rglob("*.*"))
      print(f"contents of {unity_temp}: {unity_temp_contents}")

  - id: unpack
    name: Unpack from ${{ inputs.unity-temp }} into ${{ inputs.unity-path }}
    shell: python
    env:
      unity_version: ${{ inputs.version }}
      unity_components: ${{ inputs.components }}
      unity_temp: ${{ inputs.unity-temp }}
      unity_path: ${{ inputs.unity-path }}
    run: |
      import os, sys, shutil
      from pathlib import Path

      unity_temp = Path(os.getenv("unity_temp"))
      unity_temp.mkdir(parents=True, exist_ok=True)
      unity_temp_contents = list(unity_temp.rglob("*.*"))
      print(f"contents of {unity_temp}: {unity_temp_contents}")

      unity_path = Path(os.getenv("unity_path"))
      unity_path.mkdir(parents=True, exist_ok=True)
      unity_path_contents = list(unity_path.rglob("*.*"))
      print(f"contents of {unity_path}: {unity_path_contents}")
      os.system(f"ls -alG {unity_path}")

      unity_version = str(os.getenv("unity_version"))
      unity_components = list(str(os.getenv("unity_components")).split())

      components = [f"Unity-{unity_version}.tar.xz"]
      components += map(
          lambda x: f"UnitySetup-{x}-{unity_version}.tar.xz", unity_components
      )
      print(f"components to install: {components}")

      for component in components:
          for archive in [r for r in unity_temp_contents if component == r.name]:
              print(f"extracting: {archive} for {component}")
              shutil.unpack_archive(archive, unity_path.absolute())

      unity_path_contents = list(unity_path.rglob("*.*"))
      print(f"contents of {unity_path}: {unity_path_contents}")

