name: GH (GraphQL) automatically update pull requests
description: >
  Automatically updates pull requests matching specified criteria via rebase.

inputs:
  repository:
    description: >
      Repository in `owner/repo` format for which to get the pull requests
    required: false
    default: ${{github.repository}}
  graphql-url:
    description: >
      GitHub (Enterprise) instance GRAPHQL API URL (including protocol).
    required: false
    default: ${{github.graphql_url}}
  token:
    description: >
      GitHub (Enterprise): token with at least "contents:write" permissions for the
      given repository.
      You might prefer passing a different token via secret.MY_TOKEN to allow chain
      reaction-like
      triggering of on-release workflows.
    required: false
    default: ${{github.token}}

  ## filter criteria
  filter-title:
    description: >
      Filter regular expression applied on the pull requests title.
      Empty (default) means no filter.
    required: false
    default: ''
  filter-author:
    description: >
      Filter regular expression applied on the pull requests author/submitter.
      Empty (default) means no filter.
    required: false
    default: ''
  filter-assignee:
    description: >
      Filter regular expression applied on the pull requests assignee.
      Empty (default) means no filter.
    required: false
    default: ''
  filter-branch:
    description: >
      Filter regular expression applied on the pull requests branch.
      Empty (default) means no filter.
    required: false
    default: ''

  # rate limit controls
  count:
    description: >
      Maximum amount of pull requests to update.
      Allows to stay within reasonable rate limits when there are many queued up pull requests.
    required: false
    default: 42

outputs:
  updated-pullrequests:
    description: >
      JSON representation of the updated pull requests
    value: ${{steps.update-pullrequests.outputs.updated-pullrequests}}
  count:
    description: >
      Number of updated pull requests
    value: ${{steps.update-pullrequests.outputs.count}}

runs:
  using: composite
  steps:
    - id: get-pullrequests
      uses: kagekirin/gha-py-toolbox/actions/ghgql/get-pullrequests@main
      with:
        repository: ${{inputs.repository}}
        graphql-url: ${{inputs.graphql-url}}
        token: ${{inputs.token}}
        filter-title: ${{inputs.filter-title}}
        filter-author: ${{inputs.filter-author}}
        filter-assignee: ${{inputs.filter-assignee}}
        filter-branch: ${{inputs.filter-branch}}
    - id: update-pullrequests
      uses: kagekirin/gha-py-toolbox/actions/ghgql/update-pullrequests@main
      with:
        repository: ${{inputs.repository}}
        graphql-url: ${{inputs.graphql-url}}
        token: ${{inputs.token}}
        count: ${{inputs.count}}
        pullrequests: ${{steps.get-pullrequests.outputs.pullrequests}}
        pull-request-branch-update-method: REBASE
