name: GIT tag
description: >
  Tags a given commit-ish (default: HEAD).

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  commitish:
    description: >
      Commit-ish to tag.
      Default is empty, i.e. defaults to HEAD.
    required: false
    default: ''
  tag:
    description: >
      Tag name. Required.
    required: true
  message:
    description: >
      Tag message.
      Empty string (default) creates a lightweight tag.
      Any longer message creates a fully annotated tag.
    required: false
    default: ''

runs:
  using: composite
  steps:
  - id: tag-commit
    name: Tag commit
    shell: python
    env:
      tag_path: ${{inputs.path}}
      tag_commitish: ${{inputs.commitish}}
      tag_name: ${{inputs.tag}}
      tag_message: ${{inputs.message}}
    run: |
      import os, sys

      basedir = os.getcwd()
      os.chdir(str(os.getenv("tag_path")))

      commitish = str(os.getenv("tag_commitish"))
      name = str(os.getenv("tag_name"))
      assert name is not None
      assert len(name)

      cmd = ["git", "tag"]

      message = str(os.getenv("tag_message"))
      if message and len(message):
          cmd += ["--annotate", "-m", f'"{message}"']

      cmd += [name]

      if commitish and len(commitish):
          cmd += [commitish]

      command = " ".join(cmd)
      print(command)
      err = os.waitstatus_to_exitcode(os.system(command))
      assert err == 0

      os.chdir(basedir)
      exit(err)
