name: GIT tag
description: >
  Tags a given commit-ish (default: HEAD).

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{ github.workspace }}
  commitish:
    description: >
      Commit-ish to tag.
      Defaults to HEAD.
    required: false
    default: HEAD
  tag:
    description: >
      Tag name. Required.
    required: true
  message:
    description: >
      Tag message.
      Empty string (default) creates a lightweight tag.
      Any longer message creates a fully annotated tag.
    required: false
    default: ''

runs:
  using: composite
  steps:
  - name: Tag commit
    shell: python
    env:
      tag_path: ${{ inputs.path }}
      tag_commitish: ${{ inputs.commitish }}
      tag_name: ${{ inputs.name }}
      tag_message: ${{ inputs.message }}
    run: |
      import os, sys

      basedir = os.getcwd()
      os.chdir(str(os.getenv("tag_path")))

      commitish = str(os.getenv('tag_commitish'))
      name = str(os.getenv('tag_name'))
      message = str(os.getenv('tag_message'))

      cmd = ['git', 'tag']

      if message and len(message):
        cmd += ['--annotate', '-m', f'"{message}"]

      cmd += [name, commitish]

      command = " ".join(cmd)
      print(command)
      err = os.system(command)
      assert err == 0

      os.chdir(basedir)
      exit(err)
