name: GIT rebase branch
description: >
  Rebase branch from given base branch
  Runs `git rebase [branch] [arguments ...]`.

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  branch:
    description: >
      (Head) Branch to rebase.
      If empty (default), do not switch branches before running command.
    required: false
    default: ''
  base:
    description: >
      Base branch (or commit-ish) to rebase from.
      If empty (default), uses default branch (usually main or master).
    required: true
  options:
    description: additional options to pass to rebase (e.g. --Xtheirs)
    required: false
    default: ''

runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: kagekirin/gha-py-toolbox/actions/pip/install@main
    with:
      packages: >-
        pygit2

  - id: rebase
    name: Rebase ${{inputs.options}}
    shell: python
    env:
      rebase_path: ${{inputs.path}}
      rebase_branch: ${{inputs.branch}}
      rebase_base: ${{inputs.base}}
      rebase_options: ${{inputs.options}}
    run: |
      ## actions/git/rebase-branch/action.yml#rebase
      import os, sys
      import pygit2

      basedir = os.getcwd()
      os.chdir(str(os.getenv("rebase_path")))

      rebase_branch = str(os.getenv("rebase_branch", ""))

      rebase_base = str(os.getenv("rebase_base"))
      assert rebase_base is not None

      rebase_options = str(os.getenv("rebase_options", "")).split()

      repo = pygit2.Repository(".")
      config = repo.config

      ## checkout correct branch
      if rebase_branch and not (
          rebase_branch == repo.head.shorthand or rebase_branch == repo.head.name
      ):
          branch = repo.lookup_branch(rebase_branch)
          print("branch:", branch)
          ref = repo.lookup_reference(branch.name)
          print("ref:", ref)
          repo.checkout(ref)

      os.system("git status")

      cmd = ["git", "rebase"]
      if rebase_options and len(rebase_options):
          cmd += rebase_options

      ## rebase_base cannot be empty
      cmd += [f"origin/{rebase_base}"]

      command = " ".join(cmd)
      print(command, flush=True)
      err = os.waitstatus_to_exitcode(os.system(command))
      assert err == 0

      os.chdir(basedir)
      exit(err)
