name: UNITY nuget-based setup
description: >-
  Downloads and installs Unity at the given version/changeset and for the given platform
  using NuGet.

  **WARNING: only Linux supported for now**

  **CAVEAT: requires Unity NuGet packages to be created using jobs/unity/publish-editor-nuget**

inputs:
  nuget-id:
    description: A given base NuGet ID, extracted e.g. from a nuspec.
    required: true
    default: 'UnityLinux'
  version:
    description: >-
      Unity version to install.
      Refer to https://unity.com/releases/editor/archive for the correct version.
    required: true
    default: 2021.3.21f1
  changeset:
    description: >-
      Unity changeset to install.
      Refer to https://unity.com/releases/editor/archive for the correct changeset.

      NOTE: The changeset is part of the actual download URL, i.e. https://download.unity3d.com/download_unity/{changeset}
      e.g.: https://download.unity3d.com/download_unity/1b156197d683/LinuxEditorInstaller/Unity-2021.3.21f1.tar.xz
    required: true
    default: 1b156197d683
  components:
    description: >-
      List of Unity components to install.

      Multiline, use whitespace/newline to separate items.
    required: true
    default: ''
  unity-path:
    description: path where to install Unity to
    required: true
    default: .unity

  token:
    description: >
      GitHub (Enterprise): token with "packages:read" permissions for the given repository.
    required: false
    default: ${{github.token}}
  registry:
    description: >
      Registry URL from where to fetch the package, with the terminal path `index.json`, i.e. same format as NuGet.config
      Defaults to official NuGet registry.
    required: false
    default: https://api.nuget.org/v3



outputs:
  unity-exe:
    description: full path to Unity executable
    value: ${{steps.get-unity-exe.outputs.unity-exe}}
  editor-path:
    description: full path to Unity installation folder
    value: ${{steps.get-unity-exe.outputs.editor-path}}


runs:
  using: composite
  steps:
  - id: get-nuget-id
    name: Get NuGet Id
    uses: kagekirin/gha-py-toolbox/actions/unity/get-nuget-id@main
    with:
      nuget-id: ${{ nuget-id }}
      unity-components: ${{ inputs.components }}
  - id: get-nuget-version
    name: Get NuGet version
    uses: kagekirin/gha-py-toolbox/actions/unity/get-nuget-version@main
    with:
      unity-version: ${{ inputs.version }}
      unity-changeset: ${{ inputs.changeset }}
      unity-components: ${{ inputs.components }}

  - id: get-unpack-unity
    name: Get and unpack Unity
    uses: kagekirin/gha-py-toolbox/macros/nuget/get-unpack-package@main
    with:
      path: ${{ inputs.path }}
      output-path: ${{ inputs.unity-path }}
      token: ${{ inputs.token }}
      registry: ${{ inputs.registry }}
      package: ${{ steps.get-nuget-id.outputs.nuget-id }}
      version: ${{ steps.get-nuget-version.outputs.version }}

  - id: get-unity-exe
    name: Get Unity executable
    uses: kagekirin/gha-py-toolbox/actions/unity/get-unity-exe@main
    with:
      unity-path: ${{inputs.unity-path}}
