name: DOTNET set nuspec version
description: >
  Sets the version in a given nuspec file.

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}

  version-xpath:
    description: >
      XPath expression to locate the version.
      WARNING: Defaults to //metadata/version.
    required: true
    default: //metadata/version
  nuspec-file:
    description: >
      Nuspec file (.nuspec) to check for the version.
      Defaults to *.nuspec and will take the first result.
    required: false
    default: '*.nuspec'
  version:
    description: >
      Version string to set.
      CAVEAT: not checked for validity
    required: true


outputs:
  version:
    description: the set version string
    value: ${{ steps.set-nuspec-version.outputs.version }}

runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: kagekirin/gha-py-toolbox/actions/pip/install@main
    with:
      packages: >-
        lxml

  - id: set-nuspec-version
    name: Set nuspec version
    shell: python
    env:
      inputs_path: ${{ inputs.path }}
      inputs_version_xpath: ${{ inputs.version-xpath }}
      inputs_nuspec_file: ${{ inputs.nuspec-file }}
      inputs_version: ${{ inputs.version }}
    run: |
      ## actions/dotnet/set-nuspec-version/action.yml#set-nuspec-version
      import os, sys
      from pathlib import Path
      from contextlib import chdir
      from lxml import etree

      os.chdir(os.getenv("GITHUB_WOKRDIR", "."))

      parser = etree.XMLParser(
          remove_blank_text=False,  #!< don't modify whitespace
          remove_comments=False,
          remove_pis=False,
          strip_cdata=False,
      )

      xpath = str(os.getenv("inputs_version_xpath", "//metadata/version"))
      assert xpath is not None

      nuspec_file_pattern = str(os.getenv("inputs_nuspec_file", "*.nuspec"))
      assert nuspec_file_pattern is not None

      inputs_version = str(os.getenv("inputs_version"))
      assert inputs_version is not None

      with chdir(os.getenv("inputs_path", ".")):
          nuspec_file = [f for f in Path(".").rglob(nuspec_file_pattern)][0]
          print(nuspec_file)
          assert nuspec_file.is_file()

          has_xml_declaration = nuspec_file.read_text().startswith("<?xml")

          root = etree.parse(nuspec_file, parser).getroot()
          nodes = [node for node in root.xpath(xpath)]
          nodes[0].text = inputs_version
          version = nodes[0].text
          print("version:", version, inputs_version)

          tree = etree.ElementTree(root)
          nuspec_xml = (
              (
                  etree.tostring(
                      root,
                      encoding=tree.docinfo.encoding,
                      standalone=tree.docinfo.standalone,
                      xml_declaration=True,
                  )
                  if has_xml_declaration
                  else etree.tostring(root)
              )
              .decode(encoding="utf-8")
              .replace('"/>', '" />')
          )
          print(nuspec_xml)
          nuspec_file.write_text(nuspec_xml)

          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              print(f"version={version}")
              print(f"version={version}", file=fh)


  - id: verify-outputs
    name: Verify
    shell: cat {0}
    run: |
      ## actions/dotnet/set-nuspec-version/action.yml#verify-outputs
      steps.set-nuspec-version.outputs.version      ${{steps.set-nuspec-version.outputs.version}
