name: GH GRAPHQL get pull requests
description: >
  Retrieves all OPEN pull requests matching a provided filter.
  NOTE: closed pull requests are not retrieved.

inputs:
  repository:
    description: >
      Repository in `owner/repo` format for which to get the pull requests
    required: false
    default: ${{github.repository}}
  graphql-url:
    description: >
      GitHub (Enterprise) instance GRAPHQL API URL (including protocol).
    required: false
    default: ${{github.graphql_url}}
  token:
    description: >
      GitHub (Enterprise): token with at least "contents:read" permissions for the
      given repository.
      You might prefer passing a different token via secret.MY_TOKEN to allow chain
      reaction-like
      triggering of on-release workflows.
    required: false
    default: ${{github.token}}

  filter-title:
    description: >
      Filter regular expression applied on the pull requests title.
      Empty (default) means no filter.
    required: false
    default: ''
  filter-author:
    description: >
      Filter regular expression applied on the pull requests author/submitter.
      Empty (default) means no filter.
    required: false
    default: ''
  filter-assignee:
    description: >
      Filter regular expression applied on the pull requests assignee.
      Empty (default) means no filter.
    required: false
    default: ''
  filter-branch:
    description: >
      Filter regular expression applied on the pull requests branch.
      Empty (default) means no filter.
    required: false
    default: ''
  filter-labels:
    description: >
      Filter regular expression applied on the pull requests labels.
      Empty (default) means no filter.
    required: false
    default: ''


outputs:
  ids:
    description: >
      The IDs identifying the pull requests as space-separated list.
    value: ${{steps.filter-pullrequests.outputs.ids}}
  numbers:
    description: >
      The PR numbers identifying the pull requests as space-separated list.
    value: ${{steps.filter-pullrequests.outputs.numbers}}
  branches:
    description: >
      The branches identifying the pull requests as space-separated list.
    value: ${{steps.filter-pullrequests.outputs.branches}}
  shas:
    description: >
      The respective Oids of each branch as space-separated list.
    value: ${{steps.filter-pullrequests.outputs.shas}}
  base-branches:
    description: >
      The respective base branches as space-separated list (aka base refs).
    value: ${{steps.filter-pullrequests.outputs.base_branches}}
  base-shas:
    description: >
      The respective base branch Oids as space-separated list (aka base refs).
    value: ${{steps.filter-pullrequests.outputs.base_shas}}
  pullrequests:
    description: >
      JSON representation of the pull requests
    value: ${{fromJSON(steps.filter-pullrequests.outputs.pullrequests)}}
  count:
    description: >
      Number of retrieved pull requests
    value: ${{steps.get-pullrequests.outputs.count}}

runs:
  using: composite
  steps:
  - id: prepare-inputs
    # TODO: make this a separate action
    env:
      inputs_repository: ${{inputs.repository}}
    shell: python
    run: |
      import os

      repository = str(os.getenv("inputs_repository"))
      (owner, repo) = repository.split("/")

      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"owner={owner}")
          print(f"owner={owner}", file=fh)
          print(f"repo={repo}")
          print(f"repo={repo}", file=fh)

  - id: query
    uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
    with:
      token: ${{inputs.token}}
      graphql-query: |
        query($owner: String!, $repo: String!, $count: Int!) {
          repository(owner: $owner, name: $repo)
          {
            id,
            name,
            url,
            allowUpdateBranch,
            autoMergeAllowed,
            pullRequests(
              orderBy: {
                direction : ASC,
                field : CREATED_AT,
              },
              first: $count,
              states: OPEN,
            )
            {
              nodes
              {
                baseRefOid
                baseRefName
                headRefOid
                headRefName
                id
                number
                title
                bodyText
                permalink
                resourcePath
                state
                mergeable
                url
                autoMergeRequest
                {
                  authorEmail
                  commitHeadline
                  commitBody
                  enabledAt
                  enabledBy{login}
                  mergeMethod
                }
                author{login}
                assignees(first: 10)
                {
                  nodes
                  {
                    login
                  }
                }
                labels(first: 100)
                {
                  nodes
                  {
                    id
                    name
                    color
                    description
                    url
                  }
                }
              }
            }
          }
        }
      graphql-variables: |
        {
          "owner": "${{github.repository_owner}}",
          "repo":  "${{steps.prepare-inputs.outputs.repo}}",
          "count": 100
        }
  - id: filter-pullrequests
    name: Get pull requests
    shell: python
    env:
      inputs_pullrequests: ${{toJSON(steps.query.outputs.json)}}
      inputs_filter_title: ${{inputs.filter-title}}
      inputs_filter_author: ${{inputs.filter-author}}
      inputs_filter_assignee: ${{inputs.filter-assignee}}
      inputs_filter_branch: ${{inputs.filter-branch}}
      inputs_filter_labels: ${{inputs.filter-labels}}
    run: |
      import os, sys, re, json, pprint

      inputs_pullrequests = str(os.getenv("inputs_pullrequests"))
      print("inputs_pullrequests", inputs_pullrequests)
      pulls_json = json.loads(json.loads(inputs_pullrequests))

      filter_title = str(os.getenv("inputs_filter_title"))
      filter_author = str(os.getenv("inputs_filter_author"))
      filter_assignee = str(os.getenv("inputs_filter_assignee"))
      filter_branch = str(os.getenv("inputs_filter_branch"))
      filter_labels = str(os.getenv("inputs_filter_labels"))

      pprint.pp(pulls_json)

      pulls = pulls_json["data"]["repository"]["pullRequests"]["nodes"]
      pprint.pp(pulls)

      pprint.pp([(pr["id"], pr["number"], pr["title"]) for pr in pulls])

      filtered_pulls = [pr for pr in pulls]
      if filter_title and len(filter_title) > 0:
          rx = re.compile(filter_title)
          filtered_pulls = [pr for pr in filtered_pulls if rx.search(pr["title"])]

      if filter_author and len(filter_author) > 0:
          rx = re.compile(filter_author)
          filtered_pulls = [
              pr for pr in filtered_pulls if rx.search(pr["user"].login)
          ]

      if filter_assignee and len(filter_assignee) > 0:
          rx = re.compile(filter_assignee)
          filtered_pulls = [
              pr
              for pr in filtered_pulls
              if len([ass for ass in pr["assigness"] if rx.search(ass["login"])]) > 0
          ]

      if filter_branch and len(filter_branch) > 0:
          rx = re.compile(filter_branch)
          filtered_pulls = [
              pr for pr in filtered_pulls if rx.search(pr["headRefName"])
          ]

      if filter_labels and len(filter_labels) > 0:
          rx = re.compile(filter_labels)
          filtered_pulls = [
              pr
              for pr in filtered_pulls
              if len([l for l in pr["labels"]["nodes"] if rx.match(l["name"])]) > 0
          ]

      pprint.pp(filtered_pulls)
      pprint.pp([(pr["id"], pr["number"], pr["title"]) for pr in filtered_pulls])

      ids = [pr["id"] for pr in filtered_pulls]
      pprint.pp(ids)
      numbers = [str(pr["number"]) for pr in filtered_pulls]
      pprint.pp(numbers)
      branches = [pr["headRefName"] for pr in filtered_pulls]
      shas = [pr["headRefOid"] for pr in filtered_pulls]
      base_branches = [pr["baseRefName"] for pr in filtered_pulls]
      base_shas = [pr["baseRefOid"] for pr in filtered_pulls]

      pullrequests_json = json.dumps(filtered_pulls)
      pullrequests_json_escaped = json.dumps(pullrequests_json)

      with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
          print(f"ids={' '.join(ids)}")
          print(f"ids={' '.join(ids)}", file=fh)
          print(f"numbers={' '.join(numbers)}")
          print(f"numbers={' '.join(numbers)}", file=fh)
          print(f"branches={' '.join(branches)}")
          print(f"branches={' '.join(branches)}", file=fh)
          print(f"shas={' '.join(shas)}")
          print(f"shas={' '.join(shas)}", file=fh)
          print(f"base_branches={' '.join(base_branches)}")
          print(f"base_branches={' '.join(base_branches)}", file=fh)
          print(f"base_shas={' '.join(base_shas)}")
          print(f"base_shas={' '.join(base_shas)}", file=fh)
          print(f"pullrequests={pullrequests_json_escaped}")
          print(f"pullrequests={pullrequests_json_escaped}", file=fh)
          print(f"count={len(ids)}")
          print(f"count={len(ids)}", file=fh)

  - id: verify-outputs
    name: Verify
    shell: cat {0}
    run: |
      steps.get-pullrequests.outputs.ids
      ${{steps.get-pullrequests.outputs.ids}}

      steps.get-pullrequests.outputs.numbers
      ${{steps.get-pullrequests.outputs.numbers}}

      steps.get-pullrequests.outputs.branches
      ${{steps.get-pullrequests.outputs.branches}}

      steps.get-pullrequests.outputs.shas
      ${{steps.get-pullrequests.outputs.shas}}

      steps.get-pullrequests.outputs.base_branches
      ${{steps.get-pullrequests.outputs.base_branches}}

      steps.get-pullrequests.outputs.base_shas
      ${{steps.get-pullrequests.outputs.base_shas}}

      steps.get-pullrequests.outputs.count
      ${{steps.get-pullrequests.outputs.count}}

      steps.get-pullrequests.outputs.pullrequests
      ${{steps.get-pullrequests.outputs.pullrequests}}
      ${{fromJSON(steps.get-pullrequests.outputs.pullrequests)}}
