name: NuGet Pack
description: >
  Performs nuget pack for a given nuspec file.

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}

  output-directory:
    description: >
      forwarded to option -OutputDirectory
      Specifies the directory for the created NuGet package file. If not specified, uses the current directory.
    required: false
    default: ''
  base-path:
    description: >
      forwarded to option -BasePath
      The base path of the files defined in the nuspec file.
    required: false
    default: ''
  version:
    description: >
      forwarded to option -Version
      Overrides the version number from the nuspec file.
    required: false
    default: ''
  suffix:
    description: >
      forwarded to option -Suffix
      Appends a pre-release suffix to the internally generated version number.
    required: false
    default: ''
  exclude:
    description: >
      forwarded to option -Exclude
      Specifies one or more wildcard patterns to exclude when creating a package.
      Whitespace-separated list
    required: false
    default: ''
  symbols:
    description: >
      forwarded to option -Symbols
      Determines if a package containing sources and symbols should be created. When specified with a nuspec, creates a regular NuGet package file and the corresponding symbols package.
    required: false
    default: ''
  tool:
    description: >
      forwarded to option -Tool
      Determines if the output files of the project should be in the tool folder.
    required: false
    default: false
  build:
    description: >
      forwarded to option -Build
      Determines if the project should be built before building the package.
    required: false
    default: false
  no-default-excludes:
    description: >
      forwarded to option -NoDefaultExcludes
      Prevent default exclusion of NuGet package files and files and folders starting with a dot e.g. .svn.
    required: false
    default: false
  no-package-analysis:
    description: >
      forwarded to option -NoPackageAnalysis
      Specify if the command should not run package analysis after building the package.
    required: false
    default: false
  exclude-empty-directories:
    description: >
      forwarded to option -ExcludeEmptyDirectories
      Prevent inclusion of empty directories when building the package.
    required: false
    default: false
  include-referenced-projects:
    description: >
      forwarded to option -IncludeReferencedProjects
      Include referenced projects either as dependencies or as part of the package.
    required: false
    default: false
  properties:
    description: >
      forwarded to option -Properties
      Provides the ability to specify a semicolon ";" delimited list of properties when creating a package.
    required: false
    default: ''
  min-client-version:
    description: >
      forwarded to option -MinClientVersion
      Set the minClientVersion attribute for the created package.
    required: false
    default: ''
  symbol-package-format:
    description: >
      forwarded to option -SymbolPackageFormat
      When creating a symbols package, allows to choose between the 'snupkg' and 'symbols.nupkg' format.
    required: false
    default: ''
  packages-directory:
    description: >
      forwarded to option -PackagesDirectory
      Specifies the packages folder.
    required: false
    default: ''
  solution-directory:
    description: >
      forwarded to option -SolutionDirectory
      Specifies the solution directory.
    required: false
    default: ''
  ms-build-version:
    description: >
      forwarded to option -MSBuildVersion
      Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14, 15.1, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16.0. Bydefault the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.
    required: false
    default: ''
  ms-build-path:
    description: >
      forwarded to option -MSBuildPath
      Specifies the path of MSBuild to be used with this command. This command will takes precedence over MSbuildVersion, nuget will always pick MSbuild fromthis specified path.
    required: false
    default: ''
  install-package-to-output-path:
    description: >
      forwarded to option -InstallPackageToOutputPath
      Specify if the command should prepare the package output directory to support share as feed.
    required: false
    default: ''
  output-file-names-without-version:
    description: >
      forwarded to option -OutputFileNamesWithoutVersion
      Specify if the command should prepare the package output name without the version.
    required: false
    default: ''
  config-file:
    description: >
      forwarded to option -ConfigFile
      Specify the configuration file for the pack command.
    required: false
    default: ''
  verbosity:
    description: >
      forwarded to option -Verbosity
      Display this amount of details in the output: normal, quiet, detailed.
    required: false
    default: ''


runs:
  using: composite
  steps:
  - shell: cat {0}
    run: |
      NuGet Version: 6.3.1.1
      usage: NuGet pack <nuspec | project> [options]

      Creates a NuGet package based on the specified nuspec or project file.

          Specify the location of the nuspec or project file to create a package.

      options:

      -OutputDirectory                         Specifies the directory for the created NuGet package file. If not specified, uses the current directory.
      -BasePath                                The base path of the files defined in the nuspec file.
      -Version                                 Overrides the version number from the nuspec file.
      -Suffix                                  Appends a pre-release suffix to the internally generated version number.
      -Exclude +                               Specifies one or more wildcard patterns to exclude when creating a package.
      -Symbols                                 Determines if a package containing sources and symbols should be created. When specified with a nuspec, creates a regular NuGet package file and the corresponding symbols package.
      -Tool                                    Determines if the output files of the project should be in the tool folder.
      -Build                                   Determines if the project should be built before building the package.
      -NoDefaultExcludes                       Prevent default exclusion of NuGet package files and files and folders starting with a dot e.g. .svn.
      -NoPackageAnalysis                       Specify if the command should not run package analysis after building the package.
      -ExcludeEmptyDirectories                 Prevent inclusion of empty directories when building the package.
      -IncludeReferencedProjects               Include referenced projects either as dependencies or as part of the package.
      -Properties +                       (p)  Provides the ability to specify a semicolon ";" delimited list of propertieswhen creating a package.
      -MinClientVersion                        Set the minClientVersion attribute for the created package.
      -SymbolPackageFormat                     When creating a symbols package, allows to choose between the 'snupkg' and 'symbols.nupkg' format.
      -PackagesDirectory                       Specifies the packages folder.
      -SolutionDirectory                       Specifies the solution directory.
      -MSBuildVersion                          Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14, 15.1, 15.3, 15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16.0. Bydefault the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.
      -MSBuildPath                             Specifies the path of MSBuild to be used with this command. This command will takes precedence over MSbuildVersion, nuget will always pick MSbuild fromthis specified path.
      -InstallPackageToOutputPath              Specify if the command should prepare the package output directory to support share as feed.
      -OutputFileNamesWithoutVersion           Specify if the command should prepare the package output name without the version.
      -ConfigFile                              Specify the configuration file for the pack command.
      -Help                               (?)  help
      -Verbosity                               Display this amount of details in the output: normal, quiet, detailed.
      -NonInteractive                          Do not prompt for user input or confirmations.
      -ForceEnglishOutput                      Forces the application to run using an invariant, English-based culture.

      examples:

      nuget pack

      nuget pack foo.nuspec

      nuget pack foo.csproj

      nuget pack foo.csproj -Build -Symbols -Properties Configuration=Release

      nuget pack foo.nuspec -Version 2.1.0

      For more information, visit https://docs.nuget.org/docs/reference/command-line-reference
