name: GIT lint branch
description: >
  Runs a linter (gitlint) over all commits in the current branch

inputs:
  path:
    description: path from where to run the actions
    required: false
    default: ${{github.workspace}}
  baseRef:
    description: base branch/commit-ish
    required: false
    default: main
  headRef:
    description: branch head/commit-ish
    required: false
    default: HEAD
  arguments:
    description: >
      additional arguments to pass to push (e.g. --verbose, --silence, --debug)
      DO NOT PASS `--commits` as this will be added to the call.
    required: false
    default: ''

runs:
  using: composite
  steps:
  - name: Install dependencies
    uses: kagekirin/gha-py-toolbox/actions/pip/install@main
    with:
      packages: >-
        gitlint

  - id: lint
    name: Lint
    shell: python
    env:
      inputs_path: ${{inputs.path}}
      inputs_baseref: ${{inputs.baseRef}}
      inputs_headref: ${{inputs.headRef}}
      inputs_arguments: ${{inputs.arguments}}
    run: |
      ## actions/git/lint-branch/action.yml#lint
      import os, sys
      from contextlib import chdir

      baseref = str(os.getenv("inputs_baseref", "main"))
      assert baseref is not None

      headref = str(os.getenv("inputs_headref", "HEAD"))
      assert headref is not None

      arguments = str(os.getenv("inputs_arguments", "")).split()
      assert arguments is not None

      os.chdir(os.getenv("GITHUB_WOKRDIR", "."))

      with chdir(str(os.getenv("inputs_path", "."))):
          cmd = " ".join(["gitlint"] + arguments + ["--commits", f"{baseref}..{headref}"])
          print(cmd, flush=True)
          err = os.waitstatus_to_exitcode(os.system(cmd))
          exit(err)
