name: dotnet-pack-nuget

on:
  workflow_call:
    inputs:
      runs-on:
        description: JSON string containing either a single string or the runs-on structure
        type: string
        default: '"ubuntu-latest"' # single and double high-commas required for valid JSON string
      container:
        description: URL of container image to use, empty for none
        type: string
        default: ''
      max-parallel:
        description: Number of maximum parallel runners
        type: number
        default: 4
        required: false
      configurations:
        description: |-
          JSON array of configurations to build, e.g. `'["Debug", "Release"]'`
        type: string
        required: true
        default: |-
          ["Release"]
      frameworks:
        description: |-
          JSON array of frameworks to build, e.g. `'["net9.0", "netstandard2.1"]'`
        type: string
        required: true
      projects:
        description: |-
          JSON array of projects, solutions or solution filters to build, e.g. `'["MascotCapsule.Assets.sln"]'`
        type: string
        required: true
        default: '[]'
      restore-options:
        description: >
          supplementary command line options forwarded to `dotnet restore`
          whitespace separated list.
        type: string
        required: false
        default: ''
      build-options:
        description: >
          supplementary command line options forwarded to `dotnet build`
          whitespace separated list.
        type: string
        required: false
        default: ''
      pack-options:
        description: >
          supplementary command line options forwarded to `dotnet pack`
          whitespace separated list.
        type: string
        required: false
        default: ''
    secrets:
      GHP_TOKEN:
        description: GitHub Public (non-enterprise) access token
        required: false
      GH_READONLY_TOKEN:
        description: Read-only repository access token (repo:read)
        required: true
      GH_PACKAGE_TOKEN:
        description: GitHub Package registry token (packages:read)
        required: true


jobs:
  pack-nuget:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container: ${{ inputs.container }}
    permissions:
      contents: read
      packages: read
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{ secrets.GHP_TOKEN || secrets.GITHUB_TOKEN }}
        systems: |
          python
          dotnet
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.com
    - name: Show build configurations
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ inputs.configurations }}
    - name: Show build frameworks
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ inputs.frameworks }}
    - name: Show build projects
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ inputs.projects }}

    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack@main
      with:
        lfs: true
        token: ${{ secrets.GH_READONLY_TOKEN || secrets.GITHUB_TOKEN }}
        persist-credentials: true
        configurations: ${{ join(fromJSON(inputs.configurations), ' ') }}
        frameworks: ${{ join(fromJSON(inputs.frameworks), ' ') }}
        projects: ${{ join(fromJSON(inputs.projects), ' ') }}
        filter-packages: |-
          ^(\.artifacts).*$
        restore-options: ${{ inputs.restore-options }}
        build-options: ${{ inputs.build-options }}
        pack-options: ${{ inputs.pack-options }}
      env:
        GH_NUGET_USER: ${{ github.actor }}
        GH_NUGET_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN || secrets.GITHUB_TOKEN }}
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        MSBUILDDISABLENODEREUSE: 1
