name: dotnet-release

on:
  workflow_call:
    inputs:
      dry-run:
        description: Whether to run action without effects
        type: boolean
        default: true
        required: false
    secrets:
      GHP_TOKEN:
        description: GitHub Package registry access token (packages:read)
        required: true
      GH_CHAIN_TOKEN:
        description: GitHub Package repository write token (repo:write)
        required: true


jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{ secrets.GHP_TOKEN }}
        systems: |
          python
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.com
    - uses: kagekirin/gha-py-toolbox/jobs/git/checkout-bump-tag-release@main
      with:
        token: ${{ secrets.GH_CHAIN_TOKEN }}
        persist-credentials: true
        commit-message: 'build (ci): update to '
        tag-message: 'tag:'
        name: 'GitHub CI on behalf of ${{ github.actor }}'
        bump_patch: true
        dry-run: ${{ inputs.dry-run }}
