name: dotnet-pack-nuget

on:
  workflow_call:
    inputs:
      max-parallel:
        description: Number of maximum parallel runners
        type: number
        default: 4
        required: false
      configurations:
        description: |-
          JSON array of configurations to build, e.g. `'["Debug", "Release"]'`
        type: string
        required: true
        default: |-
          ["Release"]
      frameworks:
        description: |-
          JSON array of frameworks to build, e.g. `'["net9.0", "netstandard2.1"]'`
        type: string
        required: true
      projects:
        description: |-
          JSON array of projects, solutions or solution filters to build, e.g. `'["MascotCapsule.Assets.sln"]'`
        type: string
        required: true
        default: '[]'
    secrets:
      GHP_TOKEN:
        description: GitHub Public (non-enterprise) access token
        required: true
      GH_READONLY_TOKEN:
        description: Read-only repository access token (repo:read)
        required: true
      GH_PACKAGE_TOKEN:
        description: GitHub Package registry token (packages:read)
        required: true


jobs:
  pack-nuget:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    permissions:
      contents: read
      packages: read
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{ secrets.GHP_TOKEN }}
        systems: |
          python
          dotnet
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.com
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-pack@main
      with:
        lfs: true
        token: ${{ secrets.GH_READONLY_TOKEN }}
        persist-credentials: true
        configurations: ${{ join(fromJson(inputs.configurations), ' ') }}
        frameworks: ${{ join(fromJson(inputs.frameworks), ' ') }}
        projects: ${{ join(fromJson(inputs.projects), ' ') }}
        filter-packages: |-
          ^(\.artifacts).*$
      env:
        GH_NUGET_USER: ${{ github.actor }}
        GH_NUGET_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        MSBUILDDISABLENODEREUSE: 1
