name: github-package-info

on:
  workflow_call:
    secrets:
      GHP_TOKEN:
        description: GitHub Public (non-enterprise) access token
        required: true

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{secrets.GHP_TOKEN}}
        systems: |
          python
    - name: Show infos about published package
      shell: bash
      run: |-
        echo '${{ github.event.registry_package }}'
        echo "ecosystem: ${{ github.event.registry_package.ecosystem }}"
        echo "name: ${{ github.event.registry_package.name }}"
        echo "namespace: ${{ github.event.registry_package.namespace }}"
        echo "package_type: ${{ github.event.registry_package.package_type }}"
        echo "installation_command: ${{ github.event.registry_package.package_version.installation_command }}"
        echo "name: ${{ github.event.registry_package.package_version.name }}"
        echo "npm_metadata: ${{ github.event.registry_package.package_version.npm_metadata }}"
        echo "nuget_metadata: ${{ github.event.registry_package.package_version.nuget_metadata }}"

    - name: Show infos about GitHub registry_package event
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github.event.registry_package) }}
