name: github-event-info

on:
  workflow_call:
    inputs:
      runs-on:
        description: JSON string containing either a single string or the runs-on structure
        type: string
        default: '"ubuntu-latest"' # single and double high-commas required for valid JSON string
      container:
        description: URL of container image to use, empty for none
        type: string
        default: ''
    secrets:
      GHP_TOKEN:
        description: GitHub Public (non-enterprise) access token
        required: false

jobs:
  info:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container: ${{ inputs.container }}
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{ secrets.GHP_TOKEN || secrets.GITHUB_TOKEN }}
        systems: |
          python
    - name: Show infos about GitHub
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github) }}

    - name: Show infos about event
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github.event) }}

    - id: test-query
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - id: query-schema
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        graphql-query: |-
          query {
            __schema {
              types {
                name
                kind
                description
                fields {
                  name
                  description
                }
              }
            }
          }

    - id: query-repo
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        graphql-query: |-
          query {
            __type(name: "Repository") {
              name
              kind
              description
              fields {
                name
                description
              }
            }
          }

    - id: query-pullrequest
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        graphql-query: |-
          query {
            __type(name: "PullRequest") {
              name
              kind
              description
              fields {
                name
                description
              }
            }
          }
