name: autoupdate

on:
  workflow_call:
    secrets:
      GHP_TOKEN:
        description: GitHub Public (non-enterprise) access token
        required: true
      GH_CHAIN_TOKEN:
        description: GitHub Package repository write token (repo:write)
        required: true


jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{secrets.GHP_TOKEN}}
        systems: |
          python
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.dena.jp
    - id: autoupdate-pullrequests-ordered-instamerge
      uses: kagekirin/gha-py-toolbox/jobs/gh/autoupdate-pullrequests@main
      with:
        token: ${{ secrets.GH_CHAIN_TOKEN }}
        count: 1
        filter-title: '\#ordered \#instamerge$'
    - id: autoupdate-pullrequests-instamerge
      if: ${{ steps.autoupdate-pullrequests-ordered-instamerge.outputs.count == 0 }}
      uses: kagekirin/gha-py-toolbox/jobs/gh/autoupdate-pullrequests@main
      with:
        token: ${{ secrets.GH_CHAIN_TOKEN }}
        count: 1
        filter-title: '\#instamerge$'
    - id: autoupdate-pullrequests-ordered-automerge
      if: ${{ steps.autoupdate-pullrequests-ordered-instamerge.outputs.count == 0 && steps.autoupdate-pullrequests-instamerge.outputs.count == 0 }}
      uses: kagekirin/gha-py-toolbox/jobs/gh/autoupdate-pullrequests@main
      with:
        token: ${{ secrets.GH_CHAIN_TOKEN }}
        count: 1
        filter-title: '\#ordered \#automerge$'
    - id: autoupdate-pullrequests-automerge
      if: ${{ steps.autoupdate-pullrequests-ordered-automerge.outputs.count == 0 && steps.autoupdate-pullrequests-ordered-instamerge.outputs.count == 0 && steps.autoupdate-pullrequests-instamerge.outputs.count == 0 }}
      uses: kagekirin/gha-py-toolbox/jobs/gh/autoupdate-pullrequests@main
      with:
        token: ${{ secrets.GH_CHAIN_TOKEN }}
        count: 1
        filter-title: '\#automerge$'
