name: github-event-info

on:
  workflow_call:
    secrets:
      GHP_TOKEN:
        description: GitHub Public (non-enterprise) access token
        required: true

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{secrets.GHP_TOKEN}}
        systems: |
          python
    - name: Show infos about GitHub
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github) }}

    - name: Show infos about event
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ toJSON(github.event) }}

    - id: test-query
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GH_READONLY_TOKEN }}

    - id: query-schema
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GH_READONLY_TOKEN }}
        graphql-query: |
          query {
            __schema {
              types {
                name
                kind
                description
                fields {
                  name
                  description
                }
              }
            }
          }

    - id: query-repo
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GH_READONLY_TOKEN }}
        graphql-query: |
          query {
            __type(name: "Repository") {
              name
              kind
              description
              fields {
                name
                description
              }
            }
          }

    - id: query-pullrequest
      uses: kagekirin/gha-py-toolbox/actions/ghgql/query@main
      with:
        token: ${{ secrets.GH_READONLY_TOKEN }}
        graphql-query: |
          query {
            __type(name: "PullRequest") {
              name
              kind
              description
              fields {
                name
                description
              }
            }
          }
