name: make-unittests

on:
  workflow_call:
    inputs:
      runs-on:
        description: JSON string containing either a single string or the runs-on structure
        type: string
        default: '"ubuntu-latest"' # single and double high-commas required for valid JSON string
      container:
        description: URL of container image to use, empty for none
        type: string
        default: ''
      max-parallel:
        description: Number of maximum parallel runners
        type: number
        default: 4
        required: false
      configurations:
        description: |-
          JSON array of matrix.configurations to build, e.g. `["XXX", "YYY"]` corresponding to the `include`-matrix below
        type: string
        required: true
      include:
        description: |-
          JSON array of matrix.input combinations to build, e.g. `'[{"configurations": "XXX", "commands": "projgen\nbuild\nxxx-unit-test"}, {"configurations": "YYY", "commands": "projgen\nbuild\nyyy-unit-test"}]'`
        type: string
        required: true
    secrets:
      GHP_TOKEN:
        description: GitHub Public (non-enterprise) access token
        required: false
      GH_READONLY_TOKEN:
        description: Read-only repository access token (repo:read)
        required: true
      GH_PACKAGE_TOKEN:
        description: GitHub Package registry token (packages:read)
        required: true


jobs:
  list-unittests:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container: ${{ inputs.container }}
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{ secrets.GHP_TOKEN || secrets.GITHUB_TOKEN }}
        systems: |
          python
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.com

    - name: Show build configurations
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ inputs.configurations }}
    - name: Show build include
      uses: kagekirin/gha-py-toolbox/actions/util/display-json-object@main
      with:
        object: ${{ inputs.include }}

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_READONLY_TOKEN }}
        persist-credentials: true
    - id: locate-unittests
      uses: kagekirin/gha-py-toolbox/actions/util/locate-files@main
      with:
        path: Tests
        patterns: |
          /^(?:(?!TestData).)*\.csproj$/
    outputs:
      unittests: ${{steps.locate-unittests.outputs.json}}

  run-unittests-single:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container: ${{ inputs.container }}
    needs:
    - list-unittests
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{ secrets.GHP_TOKEN || secrets.GITHUB_TOKEN }}
        systems: |
          python
          dotnet
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.com
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-test@main
      with:
        lfs: true
        token: ${{ secrets.GH_READONLY_TOKEN || secrets.GITHUB_TOKEN }}
        persist-credentials: true
        configurations: ${{ join(fromJSON(inputs.configurations), '\n') }}
        tests: ${{ join(fromJSON(needs.list-unittests.outputs.unittests), '\n') }}
        build-cache: ${{github.workspace}}/.artifacts

  run-unittests:
    if: failure()
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    container: ${{ inputs.container }}
    needs:
    - list-unittests
    - run-unittests-single
    strategy:
      fail-fast: false
      max-parallel: ${{ inputs.max-parallel }}
      matrix:
        configurations: ${{ fromJSON(inputs.configurations) }}
        include: ${{ fromJSON(inputs.include) }}
        tests: ${{fromJSON(needs.list-unittests.outputs.unittests)}}
    steps:
    - uses: kagekirin/gha-py-toolbox/macros/util/setup-system@main
      with:
        token: ${{ secrets.GHP_TOKEN || secrets.GITHUB_TOKEN }}
        systems: |
          python
          dotnet
    - uses: kagekirin/gha-py-toolbox/actions/ssh/add-public-host-key@main
      with:
        hostname: github.com
    - uses: kagekirin/gha-py-toolbox/jobs/dotnet/checkout-build-test@main
      with:
        lfs: true
        token: ${{ secrets.GH_READONLY_TOKEN || secrets.GITHUB_TOKEN }}
        persist-credentials: true
        commands: ${{ matrix.commands }}
        tests: ${{ matrix.tests }}
        build-cache: ${{github.workspace}}/.artifacts
