name: Test dotnet/add-registry action

on:
  push:
    paths:
    - actions/dotnet/add-registry
    - .github/workflows/test-dotnet-add-registry.yml
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
    - actions/dotnet/add-registry
    - .github/workflows/test-dotnet-add-registry.yml

jobs:
  add-registry:
    runs-on: ${{ matrix.platform }}
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        source:
        - nuget
        - github
        include:
          - source: nuget
            registry: https://api.nuget.org/v3/index.json
            username: KageKirin
            token: NUGET_ORG_TOKEN
          - source: github
            registry: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
            username: ${{ github.repository_owner }}
            token: GITHUB_TOKEN
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/dotnet/add-registry
      with:
        name: ${{ matrix.source }}
        registry: ${{ matrix.registry }}
        username: ${{ matrix.username }}
        token: ${{ secrets[matrix.token] }}
